lib: [
  "_build/install/default/lib/fialyzer/fialyzer.cmxs"
  "_build/install/default/lib/fialyzer/fialyzer.a"
  "_build/install/default/lib/fialyzer/fialyzer.cmxa"
  "_build/install/default/lib/fialyzer/fialyzer.cma"
  "_build/install/default/lib/fialyzer/main.ml"
  "_build/install/default/lib/fialyzer/fialyzer__Main.cmt"
  "_build/install/default/lib/fialyzer/fialyzer__Main.cmx"
  "_build/install/default/lib/fialyzer/fialyzer__Main.cmi"
  "_build/install/default/lib/fialyzer/fialyzer.ml-gen"
  "_build/install/default/lib/fialyzer/fialyzer.cmt"
  "_build/install/default/lib/fialyzer/fialyzer.cmx"
  "_build/install/default/lib/fialyzer/fialyzer.cmi"
  "_build/install/default/lib/fialyzer/opam" {"opam"}
  "_build/install/default/lib/fialyzer/META" {"META"}
]
bin: [
  "_build/install/default/bin/fialyzer" {"fialyzer"}
]
